# -*- coding: utf-8 -*-
"""Getting Schemes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15l4sob5Xkq3S6rh5T9AZvFUX-Ly0utdA
"""

import pandas as pd
from tqdm import tqdm
import string
tqdm.pandas()
import numpy as np
from sentence_transformers import SentenceTransformer, util
import matplotlib.pyplot as plt
# import seaborn as sns
# from transformers import BertTokenizer
import nltk
from nltk.corpus import stopwords
import string
# import keras_nlp
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

cd /content/drive/MyDrive/Hackathon

"""**IMPORTING PKL FILE OF EDITED CSV**

A column(embeddings) which was MiniLM embedding of information
"""

df = pd.read_pickle("embeddings_new.pkl")

import ast

model = SentenceTransformer('all-MiniLM-L6-v2')

text="i am  poor farmer"

sentence_emb = model.encode([text], convert_to_tensor=True)

from sklearn.metrics.pairwise import cosine_similarity
import tensorflow as tf

def compare(sentence_emb,scheme_embedding):
  sentence_embedding_2d = sentence_emb.numpy().reshape(1, -1)
  scheme_embedding_2d = scheme_embedding.numpy().reshape(1, -1)
  # Calculate the cosine similarity
  similarity = cosine_similarity(sentence_embedding_2d, scheme_embedding_2d)
  return similarity.item()

def get_top_k(df, sentence_emb, compare_fn, emb_col="embeddings", k=5):
    # Apply the compare function to each embedding in the column
    df = df.copy()  # avoid modifying original
    df["similarity"] = df[emb_col].apply(lambda emb: compare_fn(sentence_emb, emb))
    # Sort by similarity in descending order
    top_k = df.sort_values("similarity", ascending=False).head(k)
    return top_k

get_top_k(df, sentence_emb,compare, emb_col="embeddings", k=5)

def get_schemes(sentence_emb,df):
  return get_top_k(df, sentence_emb,compare, emb_col="embeddings", k=5)

data=get_schemes(sentence_emb,df)

output=data[["scheme_name","details","benefits","schemeCategory"]]

output

null_embeddings_indices = df[df['embeddings'].isnull()].index.tolist()

null_embeddings_indices

from google import genai

client = genai.Client(api_key="AIzaSyBiGcdP5rHCA6NWiDTrsTSv9ELnYvCznFA")

response = client.models.generate_content(
    model="gemini-2.5-flash", contents=f"""
this dataset have just 5 rows, display the schemes, followed by corresponding details, benefits,and documents required
{output}
only the info of this data should be given as output, nothing else
make it look easy to read for a normal person
"""
)
print(response.text)